
networks:
    my_network:
        driver: bridge
services:
    mysql_db:
        container_name: mysql_db
        image: "mysql:latest"
        restart: always
        networks:
            - my_network
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: 12345678
        ports:
            - 3306:3306
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            retries: 5
            start_period: 30s
            timeout: 30s
    redis:
        container_name: redis
        image: "redis:latest"
        networks:
            - my_network
        ports: 
            - 6379:6379
    # vote:
    #     build:
    #         context: ./voting-app
    #         dockerfile : Dockerfile
    #     container_name: vote-app
    #     restart: always
    #     networks:
    #         - my_network
    #     ports:
    #         - 8080:8080
    #     depends_on:
    #         - redis
    #     environment:
    #         SPRING_REDIS_HOST: redis
    #         SPRING_REDIS_PORT: 6379
    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile
        container_name: worker-app
        restart: always
        networks:
            - my_network
        ports: 
            - 8081:8081
        depends_on:
            - redis
            - mysql_db
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/mydb
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: 12345678
            SPRING_REDIS_HOST: redis
            SPRING_REDIS_PORT: 6379
    
